# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Authen-PAAS
version:      1.1.1
version_from: lib/Authen/PAAS.pm
installdirs:  site
requires:
    Config::Record:                1.1.0
    IO::Handle:                    0
    Log::Log4perl:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
